import './globals.css'
import type { Metadata } from 'next'
import ProtectedProvider from "@/components/ProtectedProvider"
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ProtectedProvider>
          { children }
        </ProtectedProvider>
      </body>
    </html>
  )
}
