import './globals.css'
import type { Metadata } from 'next'
import dynamic from 'next/dynamic'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const ProtectedProvider = dynamic(() => import('@/components/ProtectedProvider'))

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <ProtectedProvider >
            { children }
          </ProtectedProvider>
      </body>
    </html>
  )
}
